### PR TITLE
update lxqt-files

### PR DESCRIPTION
**Pull request by Besanon**
new version of previous files

### CODE REVIEW

**Comment by roddhjav** [comment]
Nice, however, you still haven't integrated all my reviews from #358.

Also, in all profiles, the attachment variable **must** be named `@{exec_path}` otherwise it would not be recognised as it by the build system.

**Comment by roddhjav** [comment]
I do not understand this:
- I have spent time reviewing your profiles and giving a lot of comments, you started improving the profiles.
- You have been asked to follow the normal git work flow (instead of editing files on Github), which after some struggle you did.

But you close the initial PR, create a new one that does not seems to include the improved version and you continue editing the file on Github?

**Comment by Besanon** [comment]
Hello ,

well, i did not quite succeed. I havent seen the Button Compare & pull after editing the profiles in git. I used:

git clone https://github.com/Besanon/apparmor.d.git
cd apparmor.d
Make the changes and commit:
git add <files changed>
git push origin 

Back in github the page repository didnt show the 

It recognized the changes yes, but the only was to sync the cloned repository (which deleted the old pull request)  and then open a new pull request
Maybe we break this down to commits of single files step by step? I some other changes of the file collection werent reflected in the pull request changes.

Am 14.07.2024 um 13:50, Alex ***@***.***> schrieb:

I do not understand this:I have spent time reviewing your profiles and giving a lot of comments, you started improving the profiles.You have been asked to follow the normal git work flow (instead of editing files on Github), which after some struggle you did.
But you close the initial PR, create a new one that does not seems to include the improved version and you continue editing the file on Github?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 
Sent with https://mailfence.com  
Secure and private email

**Comment by Besanon** [comment]
Good morning,
i will look up your old comments an i think due to my lack of proper handling the git system i will withdraw this large pull request and continue with single pull request of a singel profile. To break this down step by step ok?

**Comment by Besanon** [comment]
.

**Pull request closed without merging**
