### PR TITLE
Add lxqt desktop group & falkon

### PR DESCRIPTION
**Pull request by Besanon**
Hello, revised most of the files, deleted empty LXQT file and runit-files as well as elogind*

### CODE REVIEW

**Comment by roddhjav** [comment]
How is it different from #358? Commit are the same

**Comment by Besanon** [comment]
Hi, there are several more or less differences in files. I understand that you want to focus on systemd-related stuff. Therfore i added the repository apparmor-runit on my github site to put all the profiles which are somewhat different because of the runit init system. Far most of  your profiles work right from the start. If there is someone interested in confining runit and other init systems - i am open for contributions. 

To the current lxqt-push:
     Can you simply push [98bcf22] on [358] so we can continue from the existing review.
Yes, i would like to - but i dont know how, sorry.

Is this correct?

cd apparmor.d  (in my cloned apparmor.d directory)
git checkout -b my_contribution
git push https://github.com/roddhjav/apparmor.d/pull/383/commits/98bcf221ee8403c3fb246d9a332ab7fa48db4a5a    https://github.com/roddhjav/apparmor.d/pull/358
<username>
<token (as password)>  (I had to even look that up, user+password doesnt work)

My knowledge of github is limited to the commands you showed on the contrib-link. So, i dont know how to do single changes without making a complete new push request.

**Comment by roddhjav** [comment]
You need to connect with an ssh key (instead of a password): https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

Then, you need to push your change to your main branch where you pushed your original PR (this one is on the `Besanon-contrib` branch, it explains why it created a different PR):
```
git push origin main
```

**Comment by Besanon** [comment]
Hello,

i wasn't able to push it back, its confusing .
Are these branches needed? I says there is no difference to push - ugh

So if i don't use a branch may i just edit the cloned files unter apparmor.d an then exec
git commit    and then
git push origin main 
after authentication ?

Am 13.06.2024 um 14:09, Alex ***@***.***> schrieb:

You need to connect with an ssh key (instead of a password): https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
Then, you need to push your change to your main branch where you pushed your original PR (this one is on the Besanon-contrib branch, it explains why it created a different PR):git push origin main
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 
Sent with https://mailfence.com  
Secure and private email

**Comment by roddhjav** [comment]
Closed in favor of #358

**Pull request closed without merging**
