### PR TITLE
Unhide potential errors

### PR DESCRIPTION
**Pull request by nobody43**
This takes care of two problems:
1. User knows whether installation introduced additional errors
2. Profiles are loaded (it's not clear to a new user)

### CODE REVIEW

**Comment by roddhjav** [comment]
This should already be automatic thanks to: https://github.com/roddhjav/apparmor.d/blob/main/debian/apparmor.d.postinst

**Comment by nobody43** [comment]
It could be inactive, that's stock Ubuntu:
`apparmor.service is not active, cannot reload.`

Anyway, dumping `stderr` obscures any issues (e.g. multiple tunable definition). I'm not sure whether dumping `stdout` is needed.

What do you think of it?

**Comment by nobody43** [comment]
To reproduce:
1. define `@{XDG_SSH_DIR}` in tunables on a clean system
2. proceed with installation instructions

Result:
Installation will be finished successfully, `systemctl reload apparmor.service` errors will be obscured, and system will be in a degraded state (not all profiles loaded, regardless of the error).

**Comment by roddhjav** [comment]
Thanks. Merged, you are right, error will be easier to catch this way.

**Pull request merged**
