### PR TITLE
fix(thunar): fix "Open Terminal Here"

### PR DESCRIPTION
**Pull request by REmerald**
Thunar uses `exo-open` for the default `Open Terminal Here` action (which calls `exo-open --working-directory %f --launch TerminalEmulator`).
This commit fixes apparmor flooding the logs because it inherits the rules to the launched terminal emulator and commands run inside it.

Fixes (tested by `local/` file and reloading the service):
```
ALLOWED thunar exec @{sh_path} -> thunar//null-@{sh_path} comm=thunar requested_mask=x denied_mask=x
ALLOWED thunar//null-@{sh_path} file_mmap @{sh_path} comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} open /dev/tty comm=sh requested_mask=wr denied_mask=wr
ALLOWED thunar//null-@{sh_path} open @{lib}/gconv/gconv-modules.cache comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} getattr @{lib}/gconv/gconv-modules.cache comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} getattr owner @{HOME}/ comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} getattr owner @{HOME}/Documents/PythonLover/my-projects/ comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} getattr @{bin}/exo-open comm=sh requested_mask=r denied_mask=r
ALLOWED thunar//null-@{sh_path} exec @{bin}/exo-open -> thunar//null-@{sh_path}//null-@{bin}/exo-open comm=sh requested_mask=x denied_mask=x
...
--------------------------------------------------------------------------------------
profile thunar {
  @{sh_path} ix -> thunar//null-@{sh_path},
}
profile thunar//null-@{sh_path} {
  @{sh_path} r,

  @{bin}/exo-open rix,

  @{lib}/gconv/gconv-modules.cache r,

  owner @{HOME}/ r,
  owner @{HOME}/Documents/PythonLover/my-projects/ r,

  /dev/tty rw,
}
...
```

### CODE REVIEW

**Comment by REmerald** [comment]
I'm not sure if `@{bin}/exo-open rPx,` should be changed to `@{bin}/exo-open rPx -> child-open,`

Thunar Custom Actions are not mapped to a specific program, they're mapped to a command instead.

**Comment by roddhjav** [comment]
`@{bin}/exo-open` is included in `@{open_path}` so the only thing you need to add here is `@{sh_path} rix,`

**Comment by REmerald** [comment]
@roddhjav, if I remove the `exo-open` line, the issue comes back
`xdg-terminal-exec` is my default terminal emulator for  `exo-open`.
```
ALLOWED child-open open owner @{run}/user/@{uid}/dconf/user comm=exo-open requested_mask=wrc denied_mask=wrc
ALLOWED child-open open owner @{user_config_dirs}/dconf/user comm=exo-open requested_mask=r denied_mask=r
ALLOWED child-open exec @{bin}/xdg-terminal-exec -> child-open//null-@{bin}/xdg-terminal-exec comm=exo-open requested_mask=x denied_mask=x
...
-----------------------
profile child-open {
  @{bin}/xdg-terminal-exec ix -> child-open//null-@{bin}/xdg-terminal-exec,

  owner @{user_config_dirs}/dconf/user r,

  owner @{run}/user/@{uid}/dconf/user rw,
}
...
```

**Comment by roddhjav** [comment]
This seems normal, `@{open_path}` is used by thunar for custom action, therefore it is needed anyway. The question is more: should use use the default `child-open` profile or another (subprofile) specific for thunar action?

**Comment by REmerald** [comment]
> The question is more: should use use the default `child-open` profile or another (subprofile) specific for thunar action?

From the examples in the documentation, it can both launch applications and do command-line stuff with files. So, I'm not sure.
Is there any temporary solution I can commit, like removing `child-open`: `@{open_path} rPx,`?

**Pull request closed without merging**
