### PR TITLE
ss

### PR DESCRIPTION
**Pull request by nobodysu**

### CODE REVIEW

**Comment by nobodysu** [comment]
Errors came up in some situations. Investigating.

**Comment by nobodysu** [comment]
Removed huge scope of `ls`.

**Comment by roddhjav** [comment]
Thank for you PR.

* Can you update the `ss` profile as mentioned in https://github.com/roddhjav/apparmor.d/pull/9#issuecomment-1013726171 
* I am afraid that `grc` is the kind of tool that I mentioned in https://github.com/roddhjav/apparmor.d/pull/11#issuecomment-1013729608

**Comment by roddhjav** [comment]
Thank a lot. Merged.

**Pull request merged**
