### PR TITLE
Add support for linuxqq

### PR DESCRIPTION
**Pull request by EricLin0509**

### CODE REVIEW

**Comment by roddhjav** [comment]
linuxqq is an electron app, therefore you should use the [electron abstraction](https://apparmor.pujol.io/development/abstractions/#commonelectron) insteead of the chromium one. Also, `bwrap` is not needed here.

Please update the profile accordingly.

**Comment by EricLin0509** [comment]
OK, It should be fixed now

**Comment by roddhjav** [comment]
Thanks, merged

**Comment by roddhjav** [comment]
I was a bit fast to merge, for your future contribution, here is the commit that finish the profile fb93ac0df35346019181d96bee9624925e04fb84:
- Use `@{open_path} rPx -> child-open-strict,` instead of `xdg-open`. The child profile ensures it can only open a limited set of program.
- Use `@{lib_dirs}` inside the profile.
- The abstraction `common/electron` include `graphics`, `ssl_certs` and `nameservice-strict`

**Pull request merged**
