### PR TITLE
Partial install script

### PR DESCRIPTION
**Pull request by monsieuremre**
Please do not merge just yet. I got rid of the function and make the functionality work in a standalone script. It probably just works but it needs testing. After testing we can merge.

### CODE REVIEW

**Comment by monsieuremre** [comment]
There was a problem with regex file names like ```wl-{copy,paste}``` and ```mount.*```. I fixed it. Seems to work in all cases. It should now work for everything. Please do test before merging.

**Comment by monsieuremre** [comment]
This time I tested the whole thing. Turns out there was still an error, and I fixed it. Now it can be merged.

**Comment by roddhjav** [comment]
Thanks.

Nitpicking a bit, but why not having a function in this script and using this function for the recursive part (instead of calling the script again). It seems to me this is what you proposed initially.

**Comment by roddhjav** [comment]
Can you have test [e047da9](https://github.com/roddhjav/apparmor.d/pull/236/commits/e047da90003ac09480c90ed97f2e028d861af861). I get the same result than without the function. It may no be perfect still.

**Comment by roddhjav** [comment]
Closing, as more integration is required anyway a full implementation would most likely have to be integrated within the prebuild system.

**Pull request closed without merging**
